import { Product } from "@/types";

export const products: Product[] = [
  // ── ARIRANG ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "[ARIRANG] S/S T-Shirt (Charcoal)",
    price: 42.21,
    image: "/images/tshirt-charcoal-front.jpg",
    images: { front: "/images/tshirt-charcoal-front.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 100,
    sizes: ["S", "M", "L", "XL"],
    description: "Official ARIRANG World Tour short sleeve t-shirt in charcoal. Global Exclusive item.",
  },
  {
    id: 2,
    name: "[ARIRANG] Photo S/S T-Shirt (Black)",
    price: 42.21,
    image: "/images/tshirt-photo-black-front.jpg",
    images: { front: "/images/tshirt-photo-black-front.jpg", back: "/images/tshirt-photo-black-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 80,
    sizes: ["S", "M", "L", "XL"],
    description: "Black tee with BTS group photo graphic. Official ARIRANG World Tour merchandise.",
  },
  {
    id: 3,
    name: "[ARIRANG] S/S Tour T-Shirt (Black)",
    price: 46.50,
    image: "/images/tshirt-tour-black-front.jpg",
    images: { front: "/images/tshirt-tour-black-front.jpg", back: "/images/tshirt-tour-black-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 0,
    sizes: ["S", "M", "L", "XL"],
    description: "Official BTS WORLD TOUR [ARIRANG] S/S Tour T-Shirt in Black with tour city list.",
  },
  {
    id: 4,
    name: "[ARIRANG] S/S Crop T-Shirt (White)",
    price: 35.05,
    image: "/images/crop-tshirt-white-front.jpg",
    images: { front: "/images/crop-tshirt-white-front.jpg", back: "/images/crop-tshirt-white-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 60,
    sizes: ["S", "M", "L"],
    description: "Official BTS WORLD TOUR [ARIRANG] S/S Crop T-Shirt in White. Global Exclusive item.",
  },
  {
    id: 5,
    name: "[ARIRANG] Zip-up Hoodie (Black)",
    price: 200.00,
    image: "/images/hoodie-black-front.jpg",
    images: { front: "/images/hoodie-black-front.jpg", back: "/images/hoodie-black-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 40,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS WORLD TOUR [ARIRANG] Zip-up Hoodie in Black. Features the iconic \"ARI ARI VEGAS RA NG\" graphic print on the front with star detail along the hood. Exclusive pre-order item.",
  },
  {
    id: 6,
    name: "[ARIRANG] Hoodie & Pants Set-up (Gray)",
    price: 178.15,
    image: "/images/hoodie-gray-arirang-front.jpg",
    images: {
      front: "/images/hoodie-gray-arirang-front.jpg",
      back: "/images/hoodie-gray-arirang-back.jpg",
      detail: "/images/pants-gray-front.jpg",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 50,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS WORLD TOUR [ARIRANG] Hoodie & Pants Set-up in Gray. Complete set includes matching hoodie and sweatpants.",
  },
  {
    id: 7,
    name: "[ARIRANG] Wind Jacket (Gray)",
    price: 92.29,
    image: "/images/wind-jacket-gray-front.jpg",
    images: { front: "/images/wind-jacket-gray-front.jpg", back: "/images/wind-jacket-gray-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    description: "Official BTS WORLD TOUR [ARIRANG] Wind Jacket in Gray with ARIRANG back print.",
  },
  {
    id: 8,
    name: "[ARIRANG] Knit Cardigan (Beige)",
    price: 135.22,
    image: "/images/knit-cardigan-front.jpg",
    images: { front: "/images/knit-cardigan-front.jpg", back: "/images/knit-cardigan-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 25,
    sizes: ["S", "M", "L"],
    description: "Official BTS WORLD TOUR [ARIRANG] Knit Cardigan in Beige with logo and character back.",
  },
  {
    id: 13,
    name: "[ARIRANG] S/S Jersey",
    price: 60.81,
    image: "/images/jersey-generic-front.jpg",
    images: { front: "/images/jersey-generic-front.jpg", back: "/images/jersey-rm-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "ARIRANG",
    stock: 100,
    sizes: ["S", "M", "L", "XL"],
    description: "Official ARIRANG camo baseball jersey. Available in all 7 member variants: RM 94, JIN 92, SUGA 93, J-HOPE 94, JIMIN 95, V 95, JUNGKOOK 97.",
    memberVariants: [
      { name: "RM", number: "94", image: "/images/jersey-rm-front.jpg" },
      { name: "JIN", number: "92", image: "/images/jersey-jin-front.jpg" },
      { name: "SUGA", number: "93", image: "/images/jersey-suga-front.jpg" },
      { name: "J-HOPE", number: "94", image: "/images/jersey-jhope-front.jpg" },
      { name: "JIMIN", number: "95", image: "/images/jersey-jimin-front.jpg" },
      { name: "V", number: "95", image: "/images/jersey-v-front.jpg" },
      { name: "JUNGKOOK", number: "97", image: "/images/jersey-jungkook-front.jpg" },
    ],
  },
  // ── RUNSEOKJIN ───────────────────────────────────────────────────────────
  {
    id: 9,
    name: "[RUN SEOKJIN] EP.TOUR S/S T-Shirt (Encore Ver.)",
    price: 35.05,
    image: "/images/tshirt-encore-blue-front.jpg",
    images: { front: "/images/tshirt-encore-blue-front.jpg", back: "/images/tshirt-encore-blue-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "RUNSEOKJIN",
    stock: 70,
    sizes: ["S", "M", "L", "XL"],
    description: "Official #RUNSEOKJIN EP.TOUR S/S T-Shirt (Encore Ver.) with fish can graphic.",
  },
  {
    id: 10,
    name: "[RUN SEOKJIN] EP.TOUR L/S T-Shirt (Encore Ver.)",
    price: 42.21,
    image: "/images/tshirt-ls-encore-front.jpg",
    images: { front: "/images/tshirt-ls-encore-front.jpg", back: "/images/tshirt-ls-encore-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "RUNSEOKJIN",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    description: "Official #RUNSEOKJIN EP.TOUR Long Sleeve T-Shirt (Encore Ver.) with STAY TUNED print.",
  },
  {
    id: 11,
    name: "[RUN SEOKJIN] EP.TOUR Coach Jacket",
    price: 85.14,
    image: "/images/coach-jacket-front.jpg",
    images: { front: "/images/coach-jacket-front.jpg", back: "/images/coach-jacket-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "RUNSEOKJIN",
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    description: "Official #RUNSEOKJIN EP.TOUR Coach Jacket with RUN SEOKJIN EP TOUR back print.",
  },
  {
    id: 12,
    name: "[RUN SEOKJIN] EP.TOUR Denim Jacket",
    price: 96.58,
    image: "/images/coach-jacket-front.jpg",
    images: { front: "/images/coach-jacket-front.jpg", back: "/images/coach-jacket-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "RUNSEOKJIN",
    stock: 15,
    sizes: ["S", "M", "L", "XL"],
    description: "Official #RUNSEOKJIN EP.TOUR Denim Jacket. Limited edition exclusive item.",
  },
  // ── HOPE ON THE STAGE ────────────────────────────────────────────────────
  {
    id: 14,
    name: "[j-hope] HOPE ON THE STAGE Stripe PK T-Shirt (Multi)",
    price: 35.05,
    image: "/images/stripe-polo-front.jpg",
    images: { front: "/images/stripe-polo-front.jpg", back: "/images/stripe-polo-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "HOPE ON THE STAGE",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    description: "Official j-hope Tour 'HOPE ON THE STAGE' Stripe Polo T-Shirt with HOPE front and HOPE ON THE STAGE back.",
  },
  {
    id: 15,
    name: "[j-hope] HOPE ON THE STAGE Hoodie (Black)",
    price: 75.12,
    image: "/images/hoodie-black-front.jpg",
    images: { front: "/images/hoodie-black-front.jpg", back: "/images/hoodie-black-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "HOPE ON THE STAGE",
    stock: 35,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official j-hope Tour 'HOPE ON THE STAGE' Hoodie in Black.",
  },
  {
    id: 16,
    name: "[j-hope] HOPE ON THE STAGE S/S T-Shirt (White)",
    price: 35.05,
    image: "/images/tshirt-encore-blue-front.jpg",
    images: { front: "/images/tshirt-encore-blue-front.jpg", back: "/images/tshirt-encore-blue-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "HOPE ON THE STAGE",
    stock: 50,
    sizes: ["S", "M", "L", "XL"],
    description: "Official j-hope Tour 'HOPE ON THE STAGE' S/S T-Shirt in White.",
  },
  {
    id: 17,
    name: "[j-hope] HOPE ON THE STAGE Tour T-Shirt (Brown)",
    price: 35.05,
    image: "/images/tshirt-red-hope-front.jpg",
    images: { front: "/images/tshirt-red-hope-front.jpg", back: "/images/tshirt-red-hope-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "HOPE ON THE STAGE",
    stock: 45,
    sizes: ["S", "M", "L", "XL"],
    description: "Official j-hope Tour 'HOPE ON THE STAGE' Tour T-Shirt in Brown.",
  },
];

export const categories = ["ALL", "ARIRANG", "RUNSEOKJIN", "HOPE ON THE STAGE"];
export const mainTabs = ["'RANG' Pickup", "Album", "Tour Merch", "BT21", "Merch", "LIVE"];
