import { Product } from "@/types";

export const products: Product[] = [
  {
    id: 1,
    name: "[ARIRANG] S/S T-Shirt (Charcoal)",
    price: 42.21,
    image: "/images/tshirt-charcoal-front.jpg",
    images: { front: "/images/tshirt-charcoal-front.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 100,
    sizes: ["S", "M", "L", "XL"],
    description: "Official ARIRANG World Tour short sleeve t-shirt in charcoal.",
  },
  {
    id: 2,
    name: "[ARIRANG] Photo S/S T-Shirt (Black)",
    price: 42.21,
    image: "/images/tshirt-photo-black-front.jpg",
    images: { front: "/images/tshirt-photo-black-front.jpg", back: "/images/tshirt-photo-black-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 80,
    sizes: ["S", "M", "L", "XL"],
    description: "Black tee with BTS group photo graphic.",
  },
  {
    id: 3,
    name: "[ARIRANG] Tour Cities S/S T-Shirt (Black)",
    price: 46.50,
    image: "/images/tshirt-tour-black-front.jpg",
    images: { front: "/images/tshirt-tour-black-front.jpg", back: "/images/tshirt-tour-black-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 0,
    sizes: ["S", "M", "L", "XL"],
    description: "T-shirt featuring ARIRANG World Tour city list.",
  },
  {
    id: 4,
    name: "[ARIRANG] Camo Crop T-Shirt (White)",
    price: 35.05,
    image: "/images/crop-tshirt-white-front.jpg",
    images: { front: "/images/crop-tshirt-white-front.jpg", back: "/images/crop-tshirt-white-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 60,
    sizes: ["S", "M", "L"],
    description: "White camo cropped tee with BTS tag detail.",
  },
  {
    id: 5,
    name: "[ARIRANG] Logo S/S T-Shirt (Red)",
    price: 35.05,
    image: "/images/tshirt-red-hope-front.jpg",
    images: { front: "/images/tshirt-red-hope-front.jpg", back: "/images/tshirt-red-hope-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 90,
    sizes: ["S", "M", "L", "XL"],
    description: "Red tee with minimalist logo.",
  },
  {
    id: 6,
    name: "[ARIRANG] Hoodie & Pants Set-up (Gray)",
    price: 178.15,
    image: "/images/hoodie-gray-arirang-front.jpg",
    images: { 
      front: "/images/hoodie-gray-arirang-front.jpg", 
      back: "/images/hoodie-gray-arirang-back.jpg", 
      detail: "/images/pants-gray-front.jpg" 
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 50,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Gray hoodie and pants set with ARIRANG WORLD TOUR front print. Complete set includes matching hoodie and sweatpants.",
  },
  {
    id: 7,
    name: "[ARIRANG] Wind Jacket (Gray)",
    price: 92.29,
    image: "/images/wind-jacket-gray-front.jpg",
    images: { front: "/images/wind-jacket-gray-front.jpg", back: "/images/wind-jacket-gray-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    description: "Gray wind jacket with BTS WORLD TOUR [ARIRANG] back print.",
  },
  {
    id: 8,
    name: "[ARIRANG] Knit Cardigan (Beige)",
    price: 135.22,
    image: "/images/knit-cardigan-front.jpg",
    images: { front: "/images/knit-cardigan-front.jpg", back: "/images/knit-cardigan-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 25,
    sizes: ["S", "M", "L"],
    description: "Beige knit cardigan with logo and character back.",
  },
  {
    id: 9,
    name: "[RUN SEOKJIN] EP.TOUR S/S T-Shirt (Encore)",
    price: 35.05,
    image: "/images/tshirt-encore-blue-front.jpg",
    images: { front: "/images/tshirt-encore-blue-front.jpg", back: "/images/tshirt-encore-blue-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "RUNSEOKJIN",
    stock: 70,
    sizes: ["S", "M", "L", "XL"],
    description: "Blue tee with fish can #RUNSEOKJIN EP.TOUR graphic.",
  },
  {
    id: 10,
    name: "[RUN SEOKJIN] EP.TOUR L/S T-Shirt (Encore)",
    price: 42.21,
    image: "/images/tshirt-ls-encore-front.jpg",
    images: { front: "/images/tshirt-ls-encore-front.jpg", back: "/images/tshirt-ls-encore-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "RUNSEOKJIN",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    description: "Long sleeve with STAY TUNED #RUNSEOKJIN EP.TOUR print.",
  },
  {
    id: 11,
    name: "[RUN SEOKJIN] EP.TOUR Coach Jacket",
    price: 85.14,
    image: "/images/coach-jacket-front.jpg",
    images: { front: "/images/coach-jacket-front.jpg", back: "/images/coach-jacket-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "RUNSEOKJIN",
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    description: "Black coach jacket with #RUN SEOKJIN EP TOUR back print.",
  },
  {
    id: 12,
    name: "[RUN SEOKJIN] EP.TOUR Hoodie (Black)",
    price: 75.12,
    image: "/images/hoodie-black-front.jpg",
    images: { front: "/images/hoodie-black-front.jpg", back: "/images/hoodie-black-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "RUNSEOKJIN",
    stock: 35,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Black hoodie with RUN SEOKJIN EP.TOUR design.",
  },
  {
    id: 13,
    name: "[ARIRANG] S/S Jersey",
    price: 60.81,
    image: "/images/jersey-generic-front.jpg",
    images: { front: "/images/jersey-generic-front.jpg", back: "/images/jersey-rm-back.jpg" },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from US",
    category: "ARIRANG",
    stock: 100,
    sizes: ["S", "M", "L", "XL"],
    description: "Official ARIRANG camo baseball jersey. Available in all 7 member variants: RM 94, JIN 92, SUGA 93, J-HOPE 94, JIMIN 95, V 95, JUNGKOOK 97.",
    memberVariants: [
      { name: "RM", number: "94", image: "/images/jersey-rm-front.jpg" },
      { name: "JIN", number: "92", image: "/images/jersey-jin-front.jpg" },
      { name: "SUGA", number: "93", image: "/images/jersey-suga-front.jpg" },
      { name: "J-HOPE", number: "94", image: "/images/jersey-jhope-front.jpg" },
      { name: "JIMIN", number: "95", image: "/images/jersey-jimin-front.jpg" },
      { name: "V", number: "95", image: "/images/jersey-v-front.jpg" },
      { name: "JUNGKOOK", number: "97", image: "/images/jersey-jungkook-front.jpg" },
    ],
  },
  {
    id: 14,
    name: "[j-hope] HOPE ON THE STAGE Stripe PK T-Shirt (Multi)",
    price: 56.52,
    image: "/images/stripe-polo-front.jpg",
    images: { front: "/images/stripe-polo-front.jpg", back: "/images/stripe-polo-back.jpg" },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from US",
    category: "HOPE ON THE STAGE",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    description: "Striped polo with HOPE front and HOPE ON THE STAGE back.",
  },
];

export const categories = ["ALL", "ARIRANG", "RUNSEOKJIN", "HOPE ON THE STAGE"];
export const mainTabs = ["'RANG' Pickup", "Album", "Tour Merch", "BT21", "Merch", "LIVE"];
