import { Product } from "@/types";

export const products: Product[] = [
  // ── BTS MERCH ────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Hoodie & Pants Set-up (Gray)",
    price: 178.15,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/dglvcOwcIQglDmKe.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/dglvcOwcIQglDmKe.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS Hoodie & Pants Set-up in Gray. Complete matching set featuring ARIRANG WORLD TOUR graphic on the hoodie and logo detail on the pants.",
  },
  {
    id: 2,
    name: "Vinyl Spinner",
    price: 49.00,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/MZOfWCxvWZLncmgo.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/MZOfWCxvWZLncmgo.png",
    },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    description: "Official BTS Vinyl Spinner. A collectible chrome-finish BTS character figure with spinning mechanism.",
  },
  {
    id: 3,
    name: "[KOREA] Turntable (AT-LP60XBT BTS KR)",
    price: 349.00,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/vnWscGbySahTaMPz.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/vnWscGbySahTaMPz.png",
    },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    description: "Official BTS x Audio-Technica Turntable AT-LP60XBT BTS KR Edition. Bluetooth-enabled fully automatic belt-drive turntable with BTS branding.",
  },
  {
    id: 4,
    name: "Wind Jacket (Gray)",
    price: 92.29,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/fqVDsXOOBKtHQOZc.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/fqVDsXOOBKtHQOZc.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL"],
    description: "Official BTS ARIRANG WORLD TOUR Wind Jacket in Gray. Lightweight hooded windbreaker with ARIRANG WORLD TOUR back print.",
  },
  {
    id: 5,
    name: "Hoodie (Black)",
    price: 75.12,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/egWZyqTmBRXQSrOJ.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/egWZyqTmBRXQSrOJ.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS Hoodie in Black with paint-splatter distressed detail and BTS logo embroidery.",
  },
  {
    id: 6,
    name: "Turntable (AT-LP60XBT BTS EX)",
    price: 299.00,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/LOZbrPINxuINkFNK.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/LOZbrPINxuINkFNK.png",
    },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    description: "Official BTS x Audio-Technica Turntable AT-LP60XBT BTS EX Edition. Bluetooth-enabled fully automatic belt-drive turntable with BTS logo on the platter.",
  },
  {
    id: 7,
    name: "S/S Jersey",
    price: 60.81,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/tuwDFDHmsGQoWSSX.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/tuwDFDHmsGQoWSSX.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL"],
    description: "Official BTS ARIRANG S/S Jersey. Available in all 7 member variants: RM 94, JIN 92, SUGA 93, J-HOPE 94, JIMIN 95, V 95, JUNGKOOK 97.",
  },
  {
    id: 8,
    name: "Zip-up Hoodie (Charcoal)",
    price: 120.91,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/JvGMQycKuVMMlxVS.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/JvGMQycKuVMMlxVS.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS Zip-up Hoodie in Charcoal with distressed vintage finish, BTS logo embroidery, and floral detail.",
  },
  {
    id: 9,
    name: "Blanket",
    price: 55.00,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/HIBGNpqdolTybRtx.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/HIBGNpqdolTybRtx.png",
    },
    badges: ["EXCLUSIVE"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    description: "Official BTS Blanket featuring all 7 members in silhouette walking across the design with 'WHAT IS YOUR LOVE SONG?' text. Fringe-edge woven blanket.",
  },
  {
    id: 10,
    name: "Hoodie (Red)",
    price: 75.12,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/NZTEpuUlFTtbpDFx.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/NZTEpuUlFTtbpDFx.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS Hoodie in Red. Classic pullover hoodie with BTS branding.",
  },
  {
    id: 11,
    name: "Zip-up Hoodie (Black)",
    price: 200.00,
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/TSCgzegALrzSfcIy.png",
    images: {
      front: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663747851738/TSCgzegALrzSfcIy.png",
    },
    badges: ["EXCLUSIVE", "PRE-ORDER"],
    shipping: "Shipped from KR",
    category: "BTS",
    stock: 10,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Official BTS Zip-up Hoodie in Black with APLARI RANG graphic on the back. Premium heavyweight cotton with exclusive tour branding.",
  },
];

export const categories = ["ALL", "BTS"];
export const mainTabs = ["'RANG' Pickup", "Album", "Tour Merch", "BT21", "Merch", "LIVE"];
