// US States and Major Cities
export const US_STATES_AND_CITIES: Record<string, string[]> = {
  "AL": ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
  "AK": ["Anchorage", "Juneau", "Fairbanks", "Ketchikan", "Sitka"],
  "AZ": ["Phoenix", "Mesa", "Scottsdale", "Glendale", "Gilbert"],
  "AR": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
  "CA": ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "San Jose", "Fresno", "Long Beach", "Oakland", "Bakersfield", "Anaheim"],
  "CO": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood"],
  "CT": ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
  "DE": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
  "FL": ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Fort Lauderdale", "Tallahassee", "Coral Springs", "Clearwater"],
  "GA": ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Macon", "Marietta", "Roswell", "Alpharetta", "Valdosta"],
  "HI": ["Honolulu", "Pearl City", "Kailua", "Kaneohe", "Waipahu"],
  "ID": ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
  "IL": ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Springfield", "Peoria", "Elgin", "Waukegan", "Cicero"],
  "IN": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Bloomington"],
  "IA": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  "KS": ["Kansas City", "Wichita", "Overland Park", "Topeka", "Olathe"],
  "KY": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
  "LA": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
  "ME": ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
  "MD": ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie"],
  "MA": ["Boston", "Worcester", "Springfield", "Lowell", "Cambridge"],
  "MI": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor"],
  "MN": ["Minneapolis", "St. Paul", "Rochester", "Bloomington", "Duluth"],
  "MS": ["Jackson", "Gulfport", "Biloxi", "Hattiesburg", "Meridian"],
  "MO": ["Kansas City", "St. Louis", "Springfield", "Independence", "Columbia"],
  "MT": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
  "NE": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  "NV": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
  "NH": ["Manchester", "Nashua", "Concord", "Derry", "Rochester"],
  "NJ": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"],
  "NM": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
  "NY": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica"],
  "NC": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
  "ND": ["Bismarck", "Fargo", "Grand Forks", "Minot", "Williston"],
  "OH": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
  "OK": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
  "OR": ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro"],
  "PA": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
  "RI": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence"],
  "SC": ["Charleston", "Columbia", "Greenville", "Spartanburg", "Sumter"],
  "SD": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
  "TN": ["Memphis", "Nashville", "Knoxville", "Chattanooga", "Clarksville"],
  "TX": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Garland"],
  "UT": ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"],
  "VT": ["Burlington", "Rutland", "Montpelier", "Barre", "Bennington"],
  "VA": ["Virginia Beach", "Richmond", "Arlington", "Alexandria", "Roanoke"],
  "WA": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
  "WV": ["Charleston", "Huntington", "Parkersburg", "Morgantown", "Wheeling"],
  "WI": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
  "WY": ["Cheyenne", "Laramie", "Casper", "Gillette", "Rock Springs"],
};

export const US_STATES = Object.keys(US_STATES_AND_CITIES).sort();
